# # test="""STATE BOARD OF SCHOOL EXAMINATIONS, TAMILNADU DEPARTMENT OF GOVERNMENT EXAMINATIONS, CHENNAI - 600 006 HIGHER SECONDARY COURSE - SECOND YEAR MARK CERTIFICATE ISSUED UNDER THE AUTHORITY OF GOVERNMENT OF TAMILNADU NAME OF THE CANDIDATE <n>MURALIDHARAN S<en> DATE OF BIRTH <d>17-08-2004<ed> PERMANENT REGISTER NUMBER 2111428832 SESSION & YEAR OF ISSUE OF MARK CERTIFICATE MAY 2022 CHERAN MATRIC HR SEC SCHOOL VENNAIMALAI KARUR SCHOOL NAME Certified that the above mentioned candidate passed the following subjects in the Higher Secondary Second Year Examination. MARKS THEORY PRACTICAL INTERNAL SESSION, YEAR AND SUBJECT OBTAINED 70/90 ROLL NO. OF PASSING 20/75 10/25 FOR 100 TAMIL 080 010 090 5428955 MAY 2022 ENGLISH 073 010 083 5428955 MAY 2022 PHYSICS 057 010 5428955 MAY 2022 020 087 054 CHEMISTRY 020 010 084 5428955 MAY 2022 058 010 5428955 MAY 2022 BIOLOGY 020 088 MATHEMATICS 075 010 085 5428955 MAY 2022 <t>0517</t> ZERO FIVE ONE SEVEN TOTAL MARKS : MEDIUM OF INSTRUCTION GROUP CODE AND NAME T.M.R. CODE NO. & DATE GENERAL EDUCATION ENGLISH A2387334 20.06.2022 2503 Digitally signed on 12/08/2023 17:18:25 IST Note: 1. This certificate is generated by Digil.ocker (https://digilocker.gov.in) directly from TamilNadu Board's Database 2. This digitally signed document is legally valid as per the IT Act, 2000 when used electronically. 3. To verify this certificate, download Digil.ocker Android application from Google Play and scan the QR code on the certificate"""
# # textverifing="""STATE BOARD OF SCHOOL EXAMINATIONS, TAMILNADU DEPARTMENT OF GOVERNMENT EXAMINATIONS, CHENNAI - 600 006 HIGHER SECONDARY COURSE - SECOND YEAR MARK CERTIFICATE ISSUED UNDER THE AUTHORITY OF GOVERNMENT OF TAMILNADU NAME OF THE CANDIDATE MURALIDHARAN S DATE OF BIRTH 17-08-2004 PERMANENT REGISTER NUMBER 2111428832 SESSION & YEAR OF ISSUE OF MARK CERTIFICATE MAY 2022 CHERAN MATRIC HR SEC SCHOOL VENNAIMALAI KARUR SCHOOL NAME Certified that the above mentioned candidate passed the following subjects in the Higher Secondary Second Year Examination. MARKS THEORY PRACTICAL INTERNAL SESSION, YEAR AND SUBJECT OBTAINED 70/90 ROLL NO. OF PASSING 20/75 10/25 FOR 100 TAMIL 080 010 090 5428955 MAY 2022 ENGLISH 073 010 083 5428955 MAY 2022 PHYSICS 057 010 5428955 MAY 2022 020 087 054 CHEMISTRY 020 010 084 5428955 MAY 2022 058 010 5428955 MAY 2022 BIOLOGY 020 088 MATHEMATICS 075 010 085 5428955 MAY 2022 0517 ZERO FIVE ONE SEVEN TOTAL MARKS : MEDIUM OF INSTRUCTION GROUP CODE AND NAME T.M.R. CODE NO. & DATE GENERAL EDUCATION ENGLISH A2387334 20.06.2022 2503 Digitally signed on 12/08/2023 17:18:25 IST Note: 1. This certificate is generated by Digil.ocker (https://digilocker.gov.in) directly from TamilNadu Board's Database 2. This digitally signed document is legally valid as per the IT Act, 2000 when used electronically. 3. To verify this certificate, download Digil.ocker Android application from Google Play and scan the QR code on the certificate"""
# # name=(test.index("<n>"),test.index("<en>"))
# # print(name)
# # print(textverifing[name[0]:name[1]-4])
# # # deleting = test[name[0]:name[1]+4]
# # # nameafter = name[0],name[1]-4
# # # print(nameafter) 
# # # print(textverifing[nameafter[0]:nameafter[1]])


# test =""""் கிராமம் ( 1 ) என்ற ( 1 ) ( 1 ) ( 1 ) ( 1 ) ( 1 ) ( 1 ) ( 1 ) ( 1 ) SI. No. : 220144 ಭಾರತ್ ಇನಿ ಟ್ಯೂಟ್ ಆಫ್ ಸ್ಕೂಲಿಂಗ್ ಎಜುಕೇಷನ್(ರಿ) BHARATH INSTITUTE OF SCHOOLING EDUCATION(R) 6ರ್ನಾಟಕ ಸರ್ಕಾರದಿಂದ ಅನುಮತಿ ಮತ್ತು ಮಾನ್ಯತ APPROVED AND RECOGNISED BY GOVERNMENT OF KARNATAKA ம் கூடி *  MARKS STATEMENT ★ CERTIFICATE ಸಿನಿಯರ್ ಸೆಕೆಂಡರಿ ಎಕಾಮಿನೇಷನ್ (10+2) SENIOR SECONDARY EXAMINATION (10+2) அ ಕೆಳಗೆ ಸಮೂದಿಸಿದ ಆದ್ರರ್ಥಿಯು ಪಿನಿಯರ್ ಸೆಕೆಂಡರಿ ಎಣ್ಣಮಿರೇವನ್ (10+2) ಕೋರ್ಡ್‌ನ್ನು ಪೂರ್ಣಗೊಂಬ, ಸದರ ಪರೀಕೆಯಲ್ಲಿ ಕೆಳಗಿನ ವಿಜರಗಳೊಂದಿಗೆ ತೇರ್ಗಡೆಯಾಗಿರುತಾರೆ ಎಂದು ಪದಾಣೆಕಂಸಲಾಗಿದೆ. This is to certify that the candidate mentioned below has completed the course and passed the Senior Secondary Examination (10+2) with the following details. மான | WAP கள் செய் AUGUST 2022 PREMA N Month/Year Candidate's Name ನೊ:ಂದರೆ ಸಂಪ கலை வீச்ச LAKSHMI R Enrollment No. 220ABU01006 Mother's Name க்கிய வீர்க ENGLISH NARAYANAPPA K M Medium Father's Name ಆಸ ವಿಸಾಂಕ Date of Birth : 10-01-1999 TEN - JANUARY - ONE THOUSAND NINE HUNDRED NINETY NINE ன்ன் அலை Marks Obtained ம் மக்கள் ு முத்து In Words In Figure கத்தியு Subject க்கும் ாக்கு Code  218 217 KANNADA 100 66 00 BOI  ਦੇ 8 EIVE EICHT 100 ் 28 ENGLISH ( BB02 SEVEN SEVEN 100 57 770 HISTORY B21 SEVEN FOUR 74 ECONOMICS 100 74 1322 (C) SIX SEVEN POLITICAL SCIENCE 100 B29 FIVE EIGHT 2 SOCIOLOGY 100 ்க B28 400  600 ிராம் 2 மன்சு  ಅಕರಗಳಲ HIRST ANOHOH Result: CLASS Marks in Words : FOUR ZERO ZERO Address : No. 52/2 Sharada Arcade, Maruthi Farm, Dombarahalli, Lakshmipura (P) Davanapara (11), Bengalura - 562 162. Controller of Examina 27-10-2022"}"""
# textverifing = """தமிழநாடு மாநிலப் பள்ளிக் தே STATE BOARD OF SCHOOL EXAMINATION: வரசுத் தேர்வுகள் துறை, சென்னை DEPARTMENT OF GOVERNMENT EXAMINATIONS, CHENNA மேல்நிலைப் பள்ளிக் கல்வி இரண்டாமாண்டு மதிப்பெ HIGHER SECONDARY COURSE - SECOND YEAR WARK CER நாடு அரசின் அதிகாரத்திற்கு உட்பட்டு வரங்கப்படுக் ISSUED UNDER THE AUTHORITY OF THE GOVERNMENT OF TAMILNADU மதிப்பெண் சான்றிது தேர்வரின் பெயர் / NAME OF THE CANDIDATE வம்புகள் பட்ட பருக நடர்வுகண்ணா ச pinill curril to SESSIO AND YEAR OF ISSUE OF NARESHKANNA S MARK CERTIFICATE நிரந்தரப் பதிவெண் / PERMANENT REGISTER NUMBER பிறந்த தேசி / DATE OF BIRTH ம் 2022 26/04/2005 2111357078 MAY 2022 கழக்குறிப்பிட்டுள்ள மலநிலைப் பள்ளிக் கல்வி இரண்டாமாண்டு பொதுத் தேர்வெழுதிய மேற்காண் தேர்வா ாடங்களில் தேர்வெழுதி தேர்ச்சி பெற்றுள்ளார் எனச் சான்றளிக்கப்படுகிறது. Certified that the above mentioned candidate passed the following subjects in the Higher Secondary Second Year Examination. தேர்ச்சி பெற்ற பருவம், வருடம் பெற்ற அகமதிப்பீடு கருத்தியல் செய்முறை பா 16 மதிப்பெண்கள் 100 க்கு INTERNAL மற்றும் தேர்வெண் THEORY PRACTICAL SUBJECT MARKS SESSION, YEAR AND 70/90 10/25 20/75 OBTAINED FOR 100 ROLL NO, OF PASSING கமிழ் 5357306 MAY 2022 072 010 082 TAMIL ஆங்கிலம் 5357306 MAY 2022 070 080 010 ENGLISH இயற்பியல் 5357306 MAY 2022 039 020 010 069 PHYSICS வேதியியல் 087 5357306 MAY 2022 057 020 010 CHEMISTRY உயிரியல் 5357306 MAY 2022 045 020 010 075 BIOLOGY கணிதவியல் 049 010 059 5357306 MAY 2022 MATHEMATICS மொத்த மதிப்பெண்கள் / TOTAL MARKS : 0452 ZERO FOUR FIVE TWO பள்ளியின் பெயர் / SCHOOL NAME ( 055/TCGE0098/055026 ) J K K NATTRAJA MATRIC HR SEC SCHOOL KOMARAPALAYAM ஜே.கே. கே.நடராஜா மெட்ரிக் மேல்நிலைப்பள்ளி பயிற்றுமொழி / MEDIUM OF INSTRUCTION பாடத்தொகுப்பு எண் மற்றும் பெயர் / GROUP CODE AND NAME ENGLISH பொதுக்கல்வி / GENERAL EDUCATION அ.ம.ப. குறிமீட்டெண் & நாள் / T.M.R.CODE NO.& DATE 2503 A2324947 20.06.2022 EMIS ID No. 3305080910201800 மாநிலப் பள்ளித் தோவுகள் குழுமம் (மேலநிலை) தமிழ்நாடு MEMBER SECRETARY STATE BOARD OF SCHOOL EXAMINATIONS (HR SEC) TAMILNADU ் கிரிக்க ் கிரிக்கி குறிக்கும் குறிக்கும் குறிக்க"}"""


# # name_indices = (test.index("<n>"), test.index("<en>"))
# # print(name_indices)
# # name = textverifing[name_indices[0]:name_indices[1]-3]
# # print(name)

# # date_indices = (test.index("<d>"),test.index("<ed>"))
# # print(date_indices)
# # date = textverifing[date_indices[0]:date_indices[1]-3]
# # print(date)

# mark_indices = (test.index("<t>"),test.index("<et>")) 
# print(mark_indices)
# mark = textverifing[mark_indices[0]:mark_indices[1]-3]
# print(mark)

# # test=""
# # first=test.index("<n>")
# # print(first)
# # last=test.index("<en>"
# # )
# # print(last)
# # print(textverifing[first:last-3])

import re

def clean_text(input_text):
    # Regular expression to keep only English letters, numbers, and spaces
    cleaned_text = re.sub(r'[^A-Za-z0-9\s]', '', input_text)
    # Replace multiple spaces with a single space
    cleaned_text = re.sub(r'\s+', ' ', cleaned_text).strip()
    return cleaned_text

# Example usage22
noisy_text =""""""
cleaned_text = clean_text(noisy_text)
print("Cleaned Text:", cleaned_text)


# Birth Certificate:

{
  "name": "String, Avoid prefix or suffix denotations but Initial should be included",
  "age": "Number",
  "father_name": "String, Avoid prefix or suffix denotations but Initial should be included",
  "mother_name": "String, Avoid prefix or suffix denotations but Initial should be included",
  "date_of_birth": "Date Format (DD-MM-YYYY) Date format should be in numbers"
}



# 10th Marksheet:

{
    "name" : "String, Avoid prefix or suffix denotations but Initial should be included"
    "date_of_birth" : "Date Format (DD-MM-YYYY) Date format should be in numbers"
}

# 12th Marksheet:

{
    "name" : "String, Avoid prefix or suffix denotations but Initial should be included"
    "date_of_birth" : "Date Format (DD-MM-YYYY) Date format should be in numbers"
}

# Degree Certificate:

{
  "name": "String, Avoid prefix or suffix denotations but Initial should be included",
  "university": "String"
  "date_of_birth": "Date Format (DD-MM-YYYY) Date format should be in numbers",
  "degree": "String",
  "cgpa": "Float",
  "percentage": "Float",
  "class": "String, Class of the candidate(Such as First Class, Second Class, etc.)"
  "Qualification degree" : "String" #aicte/ugc/deb....
}

#proof of class
{
    "name" : "String, Avoid prefix or suffix denotations but Initial should be included",
    "class" : "String",
    
}
#provisional certificate

{
  "name": "String, Avoid prefix or suffix denotations but Initial should be included",
  "degree" : "String",
  "university" : "String",
  "passing year" : "Number",
  "Qualification degree" : "String" #aicte/ugc/deb....
}

#Experiance Certificate

{
   "from_date": "String of the format 'YYYY-MM-DD'",
   "to_date": "String of the format 'YYYY-MM-DD'",

}

# GATE Score Card
{
    "name": "String, Avoid prefix or suffix denotations but Initial should be included",
    "year" : "Number",
    "marks" : "Number",
    "rank" : "Number"
}

#proof of category
    
    {
        "name" : "String, Avoid prefix or suffix denotations but Initial should be included",
        "category" : "String",
        
    }
    
# optional
#proof of address
{
    "name" : "String, Avoid prefix or suffix denotations but Initial should be included",
    "address" : "String",
    
}

#phD certificate
{
  "name": "String, Avoid prefix or suffix denotations but Initial should be included",
  "university": "String",
  "Date_of_reg" : "String of the format 'YYYY-MM-DD'",
  "title_of_project": "String, any one project title",
  "no_of_paper_published": "Integer"
  "no_of_conference_attended"/"no_of_paers_published": "Integer"
}